### PR TITLE
Adding database modules with tests

### PR DESCRIPTION
**Pull request by sarthak-sopho**
Replaces PR https://github.com/elixir-cloud-aai/foca/pull/11.

Partly addresses https://github.com/elixir-cloud-aai/foca/issues/10

Only adding two functions in `db_utils.py` file. Others are specific to service and/or Celery.

### CODE REVIEW

**Comment by sarthak-sopho** [comment]
@uniqueg 
For adding the file `register_mongodb.py`, it has a dependency on some other module which has not been included till now in this archetype.

For example: https://github.com/elixir-cloud-aai/cwl-WES/blob/dev/wes_elixir/database/register_mongodb.py , if you see the imports, you'll see `from wes_elixir.ga4gh.wes.endpoints.get_service_info import get_service_info` this line.

If I include this line, it will give `import cannot be resolved` error.

So, should I create a new issue to include `register_mongodb.py` file later in `database` folder after this dependency has been added?

**Comment by uniqueg** [comment]
Thanks a lot @sarthak-sopho. I think that `register_mongodb.py` can in priniciple be added after some changes.

The line initiating the service info endpoint should be removed (and in the code of the actual services be imported and called from the main script instead). Also, some other code in that module has to be abstracted / generalized. In particular, the names and properties (which fields are indexed etc) of the database collections should be passed as arguments in order to make the functions independent of the actual service being built. Those arguments would then be passed from the main function, ideally via the app config.

**Comment by uniqueg** [comment]
As for this change, if you rephrase your PR, we can already merge it, as it seems to be complete for the `db_utils.py` module

**Comment by sarthak-sopho** [comment]
> The line initiating the service info endpoint should be removed (and in the code of the actual services be imported and called from the main script instead). Also, some other code in that module has to be abstracted / generalized. In particular, the names and properties (which fields are indexed etc) of the database collections should be passed as arguments in order to make the functions independent of the actual service being built. Those arguments would then be passed from the main function, ideally via the app config.

I think it would be better if we try to make this kind of change in one of the existing service and then replicate it here. Or should I send a PR according to your comment and then we'll work on it, if it needs improvement? That can also be done.

**Pull request merged**
