### PR TITLE
build: make project PEP 561 compliant

### LINKED ISSUE #187: build: make project PEP 561 compliant
Projects using FOCA will not benefit from type hints inside FOCA as long as FOCA does not comply with [PEP 561](https://peps.python.org/pep-0561/).

At the very least, we will need to put an empty `py.typed` file in the project root, possibly more. See [this discussion](https://stackoverflow.com/questions/62979389/is-there-a-best-practice-to-make-a-package-pep-561-compliant) for more details.

### PR DESCRIPTION
**Pull request by Rahuljagwani**
## Description

Fixes #187

**STEPS:**

1. Created `py.typed` file in the root directory.
2. Mentioned the same in `setup.py`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (or documentation does not need to be updated)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not reduced the existing code coverage

### CODE REVIEW

**Comment by Rahuljagwani** [comment]
Hi @uniqueg,

Can you review this??

**Review by uniqueg — COMMENTED** [review]
LGTM, thanks a lot @Rahuljagwani. Why did you close the PR?

**Comment by uniqueg** [comment]
Well, except for the linting error. If you run `black` on `setup.py`, commit and push, that should fix it. Or otherwise manually wrap the `package_data` dictionary argument so that it doesn't exceed the line length.

**Comment by Rahuljagwani** [comment]
> Well, except for the linting error. If you run `black` on `setup.py`, commit and push, that should fix it. Or otherwise manually wrap the `package_data` dictionary argument so that it doesn't exceed the line length.

Thanks @uniqueg, I figured out the error. I have opened a new PR #191.

**Comment by uniqueg** [comment]
Oh, you could have just pushed to the same branch and the PR would have been updated. But no worries, we'll use the new PR then :)

**Pull request closed without merging**
