### PR TITLE
add error modules

### PR DESCRIPTION
**Pull request by vivekrj0**
#12

### CODE REVIEW

**Comment by sarthak-sopho** [comment]
Hi @vivekrj0,
We are using `flake8` for linting purpose for this repo. So, check your code with flake8 before committing, else the build will fail.
Also, it is recommended to add unit tests for the modules that you are checking in. For that we are using `pytest`.
Thanks for the contribution :)

**Comment by vivekrj0** [comment]
Thanks @sarthak-sopho
I will soon add tests for this error module.

**Comment by uniqueg** [comment]
Great @vivekrj0 - please add the unit tests to this same branch. I'll merge it when test coverage is complete ;-)

**Comment by sarthak-sopho** [comment]
Hi @vivekrj0, are you working on this PR?

**Comment by vivekrj0** [comment]
yeah I am on it, tomorrow I'll add PR.

**Comment by vivekrj0** [comment]
I am closing this PR because of mismatch of name, instead I have created another with the module and the test file.

**Pull request closed without merging**
